### ISSUE TITLE
bi sorum var

### ISSUE THREAD

**Issue by javav12** [isPique/Rubber-Ducky-Bad-USB#1]
,bu auto run kodunu farklı .vbs dosyalarında yermi??, bide su senin windows security i kapatan kodda yermi yemi yemiyorsa o projeyi gelistire bilirmisin??

**Comment by isPique** [comment]
Bu autorun'ın amacı senin belirlediğin dosyayı otomatik olarak çalıştırması zaten. Yani evet oraya ne koyarsan koy otomatik olarak çalıştırıcak .exe dosyası bile koyabilirsin hiç fark etmez. Windows Security'i disable eden kodu da autorun'ın direkt olarak sadece onu çalıştırması için belirleyebilirsin. Benim burdaki amacım rubber ducky gibi davranan bir script yazabilmekti onu da .vbs dosyasındaki "WshShell.SendKeys" metodunu kullanarak yaptım zaten. İlla .vbs kullanmana gerek yok yani istediğin scripti kullanabilirsin.

**Comment by javav12** [comment]
teşekürler saolun (konuyu kapatım)
